# Datos e-commerce

In [2]:
import pandas as pd

In [12]:
df_ecommerce = pd.read_csv("data/data_ecommerce.csv", encoding = "latin1", sep = ",")
df_ecommerce.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

# **Datos Minería de Procesos**

In [13]:
df_process = pd.read_csv("data/incident_management.csv", sep = ";")
df_process.head()

,Case ID,Variant,Priority,Reporter,Timestamp,Event,Issue Type,Resolver,Report Channel,Short Description,Customer Satisfaction
0,INC0001,Variant 4,Medium,Alice,17/11/2023 11:17,Ticket created,Performance Issue,NaN,Website,Application crash,3
1,INC0001,Variant 4,Medium,Alice,17/11/2023 13:30,Ticket assigned to level 1 support,Performance Issue,Sam,Website,Application crash,3
2,INC0001,Variant 4,Medium,Alice,17/11/2023 14:06,WIP - level 1 support,Performance Issue,Sam,Website,Application crash,3
3,INC0001,Variant 4,Medium,Alice,17/11/2023 16:52,Level 1 escalates to level 2 support,Performance Issue,Michael,Website,Application crash,3
4,INC0001,Variant 4,Medium,Alice,17/11/2023 18:07,WIP - level 2 support,Performance Issue,Emma,Website,Application crash,3

In [ ]:
# minería de procesos
# dataset ==> event_log
# evento: me detalla alguna tarea (o actividad o etapa) de un caso específico de un proceso.

In [14]:
len(df_process)

242901

In [15]:
# 242901 ==> eventos

In [16]:
len(df_process["Case ID"].unique())

31588

In [17]:
# 31588 tickets (Casos)

In [18]:
len(df_process["Variant"].unique())

13

In [20]:
df_process["Variant"].value_counts()

Variant
Variant 3     95208
Variant 1     59376
Variant 7     18915
Variant 4     15638
Variant 5     14256
Variant 8      9540
Variant 6      7180
Variant 9      6250
Variant 11     3756
Variant 2      3736
Variant 10     3636
Variant 13     3388
Variant 12     2022
Name: count, dtype: int64

In [22]:
df_process[df_process["Variant"] == "Variant 3"].head()

,Case ID,Variant,Priority,Reporter,Timestamp,Event,Issue Type,Resolver,Report Channel,Short Description,Customer Satisfaction
7,INC0002,Variant 3,High,Charlie,15/08/2023 7:08,Ticket created,Performance Issue,NaN,App,Data loss issue,3
8,INC0002,Variant 3,High,Charlie,15/08/2023 8:29,Ticket assigned to level 1 support,Performance Issue,Sam,App,Data loss issue,3
9,INC0002,Variant 3,High,Charlie,15/08/2023 8:39,WIP - level 1 support,Performance Issue,Sam,App,Data loss issue,3
10,INC0002,Variant 3,High,Charlie,15/08/2023 10:11,Level 1 escalates to level 2 support,Performance Issue,Sarah,App,Data loss issue,3
11,INC0002,Variant 3,High,Charlie,15/08/2023 10:46,WIP - level 2 support,Performance Issue,Emma,App,Data loss issue,3

In [24]:
# Variante más frecuente

In [ ]:
df_process[df_process["Case ID"] == "INC0002"]

,Case ID,Variant,Priority,Reporter,Timestamp,Event,Issue Type,Resolver,Report Channel,Short Description,Customer Satisfaction
7,INC0002,Variant 3,High,Charlie,15/08/2023 7:08,Ticket created,Performance Issue,NaN,App,Data loss issue,3
8,INC0002,Variant 3,High,Charlie,15/08/2023 8:29,Ticket assigned to level 1 support,Performance Issue,Sam,App,Data loss issue,3
9,INC0002,Variant 3,High,Charlie,15/08/2023 8:39,WIP - level 1 support,Performance Issue,Sam,App,Data loss issue,3
10,INC0002,Variant 3,High,Charlie,15/08/2023 10:11,Level 1 escalates to level 2 support,Performance Issue,Sarah,App,Data loss issue,3
11,INC0002,Variant 3,High,Charlie,15/08/2023 10:46,WIP - level 2 support,Performance Issue,Emma,App,Data loss issue,3
12,INC0002,Variant 3,High,Charlie,15/08/2023 12:28,Ticket solved by level 2 support,Performance Issue,Michael,App,Data loss issue,3
13,INC0002,Variant 3,High,Charlie,15/08/2023 12:46,Customer feedback received,Performance Issue,NaN,App,Data loss issue,3
14,INC0002,Variant 3,High,Charlie,15/08/2023 12:51,Ticket closed,Performance Issue,NaN,App,Data loss issue,3

In [25]:
# Variante menos frecuente

In [ ]:
df_process[df_process["Variant"] == "Variant 12"].iloc[0]

Case ID                           INC0087
Variant                        Variant 12
Priority                              Low
Reporter                             John
Timestamp                04/04/2023 17:13
Event                      Ticket created
Issue Type                            Bug
Resolver                              NaN
Report Channel                      Email
Short Description               UI glitch
Customer Satisfaction                   4
Name: 689, dtype: object

In [27]:
df_process[df_process["Case ID"] == "INC0087"]

,Case ID,Variant,Priority,Reporter,Timestamp,Event,Issue Type,Resolver,Report Channel,Short Description,Customer Satisfaction
689,INC0087,Variant 12,Low,John,04/04/2023 17:13,Ticket created,Bug,NaN,Email,UI glitch,4
690,INC0087,Variant 12,Low,John,05/04/2023 0:25,Ticket assigned to level 2 support,Bug,Sarah,Email,UI glitch,4
691,INC0087,Variant 12,Low,John,05/04/2023 3:07,WIP - level 2 support,Bug,Sarah,Email,UI glitch,4
692,INC0087,Variant 12,Low,John,05/04/2023 11:51,Ticket solved by level 2 support,Bug,Emma,Email,UI glitch,4
693,INC0087,Variant 12,Low,John,05/04/2023 13:22,Customer feedback received,Bug,NaN,Email,UI glitch,4
694,INC0087,Variant 12,Low,John,05/04/2023 14:56,Ticket closed,Bug,NaN,Email,UI glitch,4

# **Dataset Mantenimiento**

In [29]:
df_maintenance = pd.read_csv("data/predictive_maintenance.csv")
df_maintenance.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Target,Failure Type
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,No Failure
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,No Failure
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,No Failure
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,No Failure
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,No Failure